version: '3.7'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-10.1}
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped